<?php

namespace ContactBookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GroupNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupNameRepository extends EntityRepository
{
}
